/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _SEC_INPUT_S23_SYMBOLS_H
#define _SEC_INPUT_S23_SYMBOLS_H

/* Keep the S23 structure ABI separate from the Fold/Flip input utilities. */
#ifdef CONFIG_SEC_UNIVERSAL_PROJECT
#define kunit_sec s23_kunit_sec
#define psecuretsp s23_psecuretsp
#define ptsp s23_ptsp
#define sec_cmd_exit s23_sec_cmd_exit
#define sec_cmd_init s23_sec_cmd_init
#define sec_cmd_send_event_to_user s23_sec_cmd_send_event_to_user
#define sec_cmd_set_cmd_exit s23_sec_cmd_set_cmd_exit
#define sec_cmd_set_cmd_result s23_sec_cmd_set_cmd_result
#define sec_cmd_set_cmd_result_all s23_sec_cmd_set_cmd_result_all
#define sec_cmd_set_default_result s23_sec_cmd_set_default_result
#define sec_cmd_show_result s23_sec_cmd_show_result
#define sec_cmd_show_status s23_sec_cmd_show_status
#define sec_cmd_store s23_sec_cmd_store
#define sec_cmd_virtual_tsp_read_sysfs s23_sec_cmd_virtual_tsp_read_sysfs
#define sec_cmd_virtual_tsp_write_cmd s23_sec_cmd_virtual_tsp_write_cmd
#define sec_cmd_virtual_tsp_write_cmd_factory_all \
	s23_sec_cmd_virtual_tsp_write_cmd_factory_all
#define sec_cmd_virtual_tsp_write_sysfs s23_sec_cmd_virtual_tsp_write_sysfs
#define sec_delay s23_sec_delay
#define sec_execute_tclm_package s23_sec_execute_tclm_package
#define sec_input_check_cover_type s23_sec_input_check_cover_type
#define sec_input_check_wirelesscharger_mode s23_sec_input_check_wirelesscharger_mode
#define sec_input_clear_common_hw_param s23_sec_input_clear_common_hw_param
#define sec_input_coord_event_fill_slot s23_sec_input_coord_event_fill_slot
#define sec_input_coord_event_sync_slot s23_sec_input_coord_event_sync_slot
#define sec_input_device_register s23_sec_input_device_register
#define sec_input_disable_device s23_sec_input_disable_device
#define sec_input_enable_device s23_sec_input_enable_device
#define sec_input_enabled_show s23_sec_input_enabled_show
#define sec_input_enabled_store s23_sec_input_enabled_store
#define sec_input_gesture_report s23_sec_input_gesture_report
#define sec_input_get_common_hw_param s23_sec_input_get_common_hw_param
#define sec_input_get_fod_info s23_sec_input_get_fod_info
#define sec_input_get_lcd_id s23_sec_input_get_lcd_id
#define sec_input_handler_start s23_sec_input_handler_start
#define sec_input_parse_dt s23_sec_input_parse_dt
#define sec_input_pinctrl_configure s23_sec_input_pinctrl_configure
#define sec_input_power s23_sec_input_power
#define sec_input_print_info s23_sec_input_print_info
#define sec_input_proximity_report s23_sec_input_proximity_report
#define sec_input_register_vbus_notifier s23_sec_input_register_vbus_notifier
#define sec_input_release_all_finger s23_sec_input_release_all_finger
#define sec_input_set_fod_info s23_sec_input_set_fod_info
#define sec_input_set_fod_rect s23_sec_input_set_fod_rect
#define sec_input_set_grip_type s23_sec_input_set_grip_type
#define sec_input_set_temperature s23_sec_input_set_temperature
#define sec_input_sysfs_create s23_sec_input_sysfs_create
#define sec_input_sysfs_remove s23_sec_input_sysfs_remove
#define sec_input_unregister_vbus_notifier s23_sec_input_unregister_vbus_notifier
#define sec_tclm_case s23_sec_tclm_case
#define sec_tclm_check_cal_case s23_sec_tclm_check_cal_case
#define sec_tclm_debug_info s23_sec_tclm_debug_info
#define sec_tclm_initialize s23_sec_tclm_initialize
#define sec_tclm_parse_dt s23_sec_tclm_parse_dt
#define sec_tclm_parse_dt_dev s23_sec_tclm_parse_dt_dev
#define sec_tclm_root_of_cal s23_sec_tclm_root_of_cal
#define sec_tclm_test_on_probe s23_sec_tclm_test_on_probe
#define stui_tsp_enter s23_stui_tsp_enter
#define stui_tsp_exit s23_stui_tsp_exit
#define stui_tsp_init s23_stui_tsp_init
#define stui_tsp_type s23_stui_tsp_type
#define tclm_test_command s23_tclm_test_command
#endif

#endif
